var textList = ["Nettle is a goblin, short statured even for one of her kind, if I were to make a guess, I would say taller than a pumpkin, though maybe not taller than a pumpkin with a couple of cabbages stacked on top. Though her height matches her temper, I guess the universe evens things out in its own way.", 
			"", 
            "Nettle lives just off of the beaten bath, on the outskirts of the bustling town of Dirtfarm (really creative name, I know). Though it's quite peaceful, being so removed from everything. One of the rare places where you can just, forget the world. Get lost in a good book.",  
            "I imagine Nettle has a lot of time to think about nothing in particular.", 
            "Nettle lives in a small, dusty house with her parents. On the outskirts of a bustling town. It's peaceful in a way, being so far from everything.", 
            "In the middle of said town is a school, an institution of learning. Nettle goes there every day. Not by her own choice of course, for her parents tell her to go (and it's also kinda the law or whatever). Not to imply that she dislikes school, in fact, one could say she quite enjoys \"learning\".", 
            "Sure teachers tend to drone on and on about whatever, it's in their nature I suppose. Not that Nettle really minded. School gives her something to expect, Nettle knows what's coming, Math, English, And Science, that's all she has to worry about.", 
            "\"Bla Bla Bla Bla,\" the teacher droned on (it's not really important, so you don't really need to hear it).", 
            "\"Bla Bla Bla Bla.\"", 
            "\"Bla Bla.\"", 
            "\"WHACK! WHACK! WHACK!\"", 
            "\"Ahem\" (sorry yeah, turns out it was important after all)  the teacher grumbled.", 
            "\"AS I WAS SAYING, allow me to introduce those of you who have not met her yet, Ms Johnson, your counselor.\"", 
            "\"She would like to have a few words with you today.\"",  
            "Ms Johnson was a short… \"Round\" woman. Who wore a large bushy jacket, with a fur lined collar that was similar to a lion's mane. She also had a sharp sweet scent of perfume that seemed to permeate every room she entered.",  
            "\"Hello, hello my wonderful students, it's come time for you all to start thinking about life after high school.\"", 
            "\"Huh?\" muttered Nettle, dumbfounded.",
            "\"Now, how many of you have some idea of what you will be doing?\"", 
            "It seemed like everyone (except the teachers of course) raised their hands except Nettle. Like she was a sad, lonely stump, in a forest where every other tree was flourishing and thriving.", 
            "\"Good, good\" the counselor said with a satisfied smirk on her face. \"I was worried that you all hadn't even started thinking about these important things yet.\"", 
            "\"The choices you make here, could affect the entire rest of your life\" She said, leaning in with a stoic expression.", 
            "Ms Johnson carried on with the rest of her presentation, the kinda type that's really only useful for the handful of people who are going to college at whatever institution the high school board of directors or whatever wants you to do.", 
            "Most of it ended up going over Nettle's head anyway, she ended up passing most of the time by staring at a speck of mold on the ceiling.", 
            "As the room emptied out, Nettle approached the woman.", 
            "\"Miss?\" She stuttered.", 
            "\"Yes?\"", 
            "\"Now, that stuff was reallllllly helpful and all, but I'm still not sure what I should do after graduation\"",  
            "\"Hmmm…\" the counselor responded, tapping her pen repeatedly upon a nearby desk.", 
            "\"Tap, tap, tap.\"", 
            "\"Well, naturally you want to make money right?\"", 
            "\"Sure, why not?\"",   
            "\"Become a doctor then, or a merchant, really, what you do doesn't matter as long as there is a good amount of money involved.\"",  
            "Nettle looked up at the taxidermied deer head mounted just above the chalk board. Its fur was matted down into sleek, clean lines. And while the animal's eyes reflected some of the light around it, they remained still, unmoving, and dull.",  
            "\"But I've never done any doctor stuff before.\"", 
            "\"That's what college is for,\" the counselor pulled out a pipe, lit it, and breathed in. \"Learn some new s-perences and that\", tobacco smell filled the room.",
            "\"Thanks, that was really helpful.\"", 
            "\"You're welcomee.\"", 
            "\"UGH,\" Nettle grumbled as she left the room.", 
	
			"(Sometime later that day)", 
			
			"Rounding the corner, Nettle came around to a small field with various vegetables planted in it. Carrots, cabbages, and potatoes to name a few. Off to the side is a small chicken coop with a wired fence surrounding it, feathers are scattered around the perimeter of the hut. In the center of the field is a house, not exactly a very large home, even for goblins.",   
            "Each window, door and wooden panel is worn in some way, with dirt and dust wedged into every nook and cranny. Arriving at the door, Nettle pushed it open. The interior wasn't much nicer, but one major difference is how dark each room of the house is. With the sun just starting to set, the whole place is cast into a dim twilight. Walking though the house, Nettle arrived at the dining room,",  
            "which had a large table set in the center (really it's a wonder how they got the table into there, seeing as it's twice the size as the only doorway to the room). A top was the usual dinner stuff. Fork, knives, spoons, bowls with food inside. All that stuff In the center was a singular candle, illuminating the two goblins who sat at the end of the table farthest from the door, both of whom had already started eating.", 
            "Sitting down, Nettle followed in the example of her parents.", 
            
            "\"Hey mum? Dad?\" Nettle said, swallowing a piece of chicken.", 
            "\"Mmmhh?\" Her father grunted.", 
            "\"What should I do once I graduate?\"",  
            "\"Well, I always thought you would come work with us on the farm\" her mom chimed in.",
            "\"Wouldn't that be nice? You wouldn't have to worry about rent, we can help you on anything that you need help with.\"",  
            "\"Mmhmm\" the father grunted.",
            "\"...\"",
            "\"No,\" Nettle responded.", 
            "\"I don't want to do that, I wanna see the world, not spend my whole life stuck farming in this town.\"", 
            "\"Oh honey\", her mother cooed.",
            "\"You're young, and, not to imply that you are stupid or anything like that, but you don't understand the world well enough yet, once you are older, you'll understand that this is the right decision.\"", 
            "Nettle poked a piece of potato with her fork, pushing it around on her plate.", 
            "\"Ok\" Nettle responded.",
            "The rest of dinner passed in silence.",

			"(The next morning)",
		
		
			"Nettle was walking down a long dirt path, on the right side was a large corn field that ran for the span of the path. And on the left was a grass expanse, that was shorn to about Nettle's knee caps. A light breeze blew through the area, causing the field, and other various plant life to rustle as nettle trotted past.", 
		            "The sky was a light, pastel blue. Casting its brightness down onto the plants beneath it, bringing out a light green accent from the surrounding life.",
			"Off in the distance is a small dot that grows slowly bigger as Nettle continues walking forward. As she goes on, Nettle starts to make out a carriage, the size of a small shed. Adorned on the tops and sides is an assortment of bags, barrels, and nets carrying all manner of goods and trinkets.", 
			"As Nettle gets closer, she can make out what seems to be a man sitting atop the card, a spindly guy with long limbs, limbs that almost seem a bit too long for his body. Like someone swapped his legs and arms with someone else's.",  
			"\"Hello! Hello!\", the man called. It seems that he has noticed Nettle walking up behind him",  
			"\"Welcome to Nickel and Bank's shop and emporium!\"",
			"\"...\"",  
			"Nettle swiveled her head back and forth over the cart.",  
			"\"I only see one person.\"", 
		            "\"Bank isn't here right now.\"",  
		            "\"Sure,\" Nettle said sarcastically.",    
			"\"So that makes you Nickel then?\"", 
			"A hearty laugh issued from the man's slim throat.", 
			"\"Of course!\"",  
			"\"Now that we are properly introduced, why don't you take a look around my wears?\" Nickel said, jabbing an eyebrow at the containers behind him.", 
			"\"I don't have any money\" Nettle deadpanned.", 
			"\"Oh\" Nickel's voice dropped two registers.",  
			"\"Then what are you wasting my time for? Scram!\"",   
			"Nettle looked left. And then right.", 
		            "\"To where exactly? There's nothing out here.\"", 
		            "\"I don't know, scramble off into the forest or something.\"",  
			"Nettle grabbed a handful of dirt and threw it at Nickel.",   
			"\"HEY! YOU LITTLE!\"",   
		
			"\"...\"",   
		
			"The dirt path itself was quite dry and dusty, mainly because it had been a few weeks since there had been rain. Thus causing every movement to create clouds of dirt, tinting the shoes of those who walked through it a light brown.",  
			"\"Soo, uh.\"", 
			"\"Did you go to college?\"", 
			"\"No!\"",  
			"\"Of course not! You think school would teach you how to do something like this?\"", 
            "Nickel pulled out a coin from a pocket in his trousers, did some hand gestures and movements that Nettle found hard to follow, and made two coins appear in its place.", 
            "\"Wow, that's cool n all, but how is that supposed to be useful?\" Nettle asks.", 
            "\"Ah, well you're just not young enough to get it.\"", 
            "\"I don't see how age applies here.\"",  
            "\"Little kids are stupid, they'll believe anything and everything you tell them.\"", 
            "\"Huh.\"",  
            "There weren't many trees near the path, but a few would pop up every now and then. With dark brown trunks, and green leaves that rustled along with the wind. They were large and tall, seemingly taller than those in a forest. But perhaps the amount of trees desensitizes one to the verticality of the trees in a wooded area.",  
            "\"Ok, but like what did you do after you graduated high school?\"", 
            "\"Well, let's see here\" Said the knobby man, his brow furrowed, his eyes squinted.", 
            "\"I worked as a shoe shiner for a few years, then went on to build houses for a time, worked for the king as a tax collector, did bartending for a bit there, I then went back to building houses, after that back to a shoe shiner, guess I was feeling nostalgic or something, Ran messages for ye old mart of wall, Worked at the front counter at ye old mart, stocked shelves at ye old walmart, really a lotta of walmart for a bit there.\"",    
            "\"And now I'm here, a traveling salesman of sorts.\"",  
            "...", 
            "\"Wow.\"",  
            "\"That's a lot.\"",   
            "\"One might call me a jack of all trades.\"",  
            "\"Totally\" Nettle responded.",
            "\"But what made you want to do all that stuff?\"",   
            "\"Not really some greater reason kid, besides money, or something sounding interesting.\"", 
            "\"Why so many then?\" Questioned the goblin.",
            "\"Why not? Might as well try a bunch of new things and possibly fail at some of them, then do somethin you don't wanna do.\"", 
            "\"Huh\"", 
            
            "Eventually the path split, and the two parted ways. Nettle never saw Nickel or his strange cart again. She wouldn't say that her questions had really been answered, but the talk Nettle had with Nickel got her thinking about what she wanted to do, and she guessed that was good enough, not relying on other people to answer her questions and all that.",  
            
            "Also what on earth is a \"Walmart\".",  
            ]; 
